### ISSUE TITLE
Design proposition

### ISSUE THREAD

**Issue by aveuiller** [APISENSE/bee-android#1]
Since we would like the same design identity on both applications, the discussion will be done on the [bee-ios design related issue](https://github.com/APISENSE/bee-ios/issues/2).

You can refer to the [Android UI Guidelines](http://developer.android.com/training/best-ui.html) to build your design.

**Comment by Tibooh** [comment]
Ce genre de maquette vous convient il ? Ça reste encore schématique bien sûr.
![login2](https://cloud.githubusercontent.com/assets/9962847/13073498/5fa6c4d4-d49f-11e5-8705-45608318e90b.jpeg)

Nous allons vous envoyer une série de propositions d'ici demain.

Pour les couleurs, est ce que vous souhaitez une application aux couleurs de votre logo (jaune et noir) ou bien nous sommes libre des couleurs ?

**Comment by rouvoy** [comment]
Merci de respecter les consignes indiquées dans le billet initial et de poster vos messages sur le [bon billet](https://github.com/APISENSE/bee-ios/issues/2).
