### ISSUE TITLE
Notification appears back without starting Bee

### ISSUE THREAD

**Issue by surli** [APISENSE/bee-android#43]
The bee notification appears back after discarding it, even if I did not start back bee. 
Actually I even did not have any crop running on the phone, so I really don't understand why the service seem starting. 
I did not restart the phone, and apparently the notification appears back every few hours (something like 7 to 9 hours)

**Comment by aveuiller** [comment]
The service is started as [sticky](https://developer.android.com/reference/android/app/Service.html#START_STICKY), even when set in background by the user. So when it is effectively killed by the system, it will be restarted as a foreground service again.

We will provide an update of the SDK to avoid this behavior, the service will be set as non sticky when stopped by the user.

**Comment by abourdon** [comment]
Note that there is also able to start/stop collect, even if there is no crop running. Is there a way to hide or grayed the start/stop button if there is no crop running?

**Comment by aveuiller** [comment]
The fix has been released in `2.0.4`
